name: buildx

on:
  push:
    branches:
      - 'builder'
  pull_request:

env:
  DOCKERHUB_USER: wiserain
  IMAGE_NAME: wiserain/libtorrent

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    if: (github.event_name != 'watch') || (github.actor == github.event.repository.owner.login)
    strategy:
      matrix:
        distro: [ubuntu18.04, ubuntu20.04, ubuntu20.10]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to docker.io
        uses: docker/login-action@v1 
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
      - 
        name: Buildx and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.distro }}/.
          file: ${{ matrix.distro }}/Dockerfile
          tags: |
            ${{ env.IMAGE_NAME }}:builder-${{ matrix.distro }}
            ghcr.io/${{ env.IMAGE_NAME }}:builder-${{ matrix.distro }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          build-args: |
            LIBTORRENT_VER=${{ env.LIBTORRENT_VER }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            ${{ env.IMAGE_NAME }}:builder-${{ matrix.distro }}
            ghcr.io/${{ env.IMAGE_NAME }}:builder-${{ matrix.distro }}
