name: docker-buildx

on:
  watch:
    types: [started]
  push:
    branches:
      - '*'
      - '!master'   # excludes master
    tags:
      - '*'
  pull_request:

env:
  DOCKERHUB_USER: wiserain
  DOCKERHUB_REPO: libtorrent
  LIBTORRENT_VER: "2.0.0"

jobs:
  alpine310-py2:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=distro::alpine3.10
          echo ::set-output name=pymver::2
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}
          dockerFile: ${{ steps.vars.outputs.distro }}/Dockerfile
          buildArg: LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},PY_MAJOR_VER=${{ steps.vars.outputs.pymver }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}

  alpine310-py3:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=distro::alpine3.10
          echo ::set-output name=pymver::3
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}
          dockerFile: ${{ steps.vars.outputs.distro }}/Dockerfile
          buildArg: LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},PY_MAJOR_VER=${{ steps.vars.outputs.pymver }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}

  alpine311-py2:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=distro::alpine3.11
          echo ::set-output name=pymver::2
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}
          dockerFile: ${{ steps.vars.outputs.distro }}/Dockerfile
          buildArg: LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},PY_MAJOR_VER=${{ steps.vars.outputs.pymver }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}

  alpine311-py3:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=distro::alpine3.11
          echo ::set-output name=pymver::3
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}
          dockerFile: ${{ steps.vars.outputs.distro }}/Dockerfile
          buildArg: LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},PY_MAJOR_VER=${{ steps.vars.outputs.pymver }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}

  alpine312-py3:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=distro::alpine3.12
          echo ::set-output name=pymver::3
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}
          dockerFile: ${{ steps.vars.outputs.distro }}/Dockerfile
          buildArg: LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},PY_MAJOR_VER=${{ steps.vars.outputs.pymver }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}

  ubuntu1910-py2:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=distro::ubuntu19.10
          echo ::set-output name=pymver::2
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}
          dockerFile: ${{ steps.vars.outputs.distro }}/Dockerfile
          buildArg: LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},PY_MAJOR_VER=${{ steps.vars.outputs.pymver }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}

  ubuntu1910-py3:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=distro::ubuntu19.10
          echo ::set-output name=pymver::3
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}
          dockerFile: ${{ steps.vars.outputs.distro }}/Dockerfile
          buildArg: LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},PY_MAJOR_VER=${{ steps.vars.outputs.pymver }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}

  ubuntu2004-py3:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=distro::ubuntu20.04
          echo ::set-output name=pymver::3
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}
          dockerFile: ${{ steps.vars.outputs.distro }}/Dockerfile
          buildArg: LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},PY_MAJOR_VER=${{ steps.vars.outputs.pymver }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}

  ubuntu2010-py3:
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=distro::ubuntu20.10
          echo ::set-output name=pymver::3
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run Buildx
        uses: ilteoood/docker_buildx@master
        with:
          imageName: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          tag: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}
          dockerFile: ${{ steps.vars.outputs.distro }}/Dockerfile
          buildArg: LIBTORRENT_VER=${{ env.LIBTORRENT_VER }},PY_MAJOR_VER=${{ steps.vars.outputs.pymver }}
          publish: true
          platform: linux/amd64,linux/arm/v7,linux/arm64
          dockerHubUser: ${{ env.DOCKERHUB_USER }}
          dockerHubPassword: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Send Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          description: |
            Image: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
            Tags: latest-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }},${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.distro }}-py${{ steps.vars.outputs.pymver }}

  make-release:
    needs:
      - alpine310-py2
      - alpine310-py3
      - alpine311-py2
      - alpine311-py3
      - alpine312-py3
      - ubuntu1910-py2
      - ubuntu1910-py3
      - ubuntu2004-py3
      - ubuntu2010-py3
    runs-on: ubuntu-latest
    if: github.actor == github.event.repository.owner.login
    steps:
      - 
        name: Load Variables
        id: vars
        run: |
          echo ::set-output name=date::$(date -u +'%y%m%d')
          echo ::set-output name=tags::"alpine3.10-py2 alpine3.10-py3 alpine3.11-py2 alpine3.11-py3 alpine3.12-py3 ubuntu19.10-py2 ubuntu19.10-py3 ubuntu20.04-py3 ubuntu20.10-py3"
          echo ::set-output name=github_desc::$(curl -sX GET https://api.github.com/repos/wiserain/docker-libtorrent | jq -r .description)
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Generate Release Assets
        run: |
          chmod +x ./release.sh
          ./release.sh ${{ env.LIBTORRENT_VER }} "${{ steps.vars.outputs.tags }}"
      - 
        name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.date }}
          release_name: libtorrent-${{ env.LIBTORRENT_VER }}-${{ steps.vars.outputs.date }}
          body: Auto-generated release
          draft: true
          prerelease: false
      - 
        name: Upload Assets to Release with a wildcard
        uses: csexton/release-asset-action@v2
        with:
          pattern: "release/*.tar.gz"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
      - 
        name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ env.DOCKERHUB_USER }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASS }}
        with:
          destination_container_repo: ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_REPO }}
          provider: dockerhub
          short_description: ${{ steps.vars.outputs.github_desc }}
          readme_file: 'README.md'
